import { messageIds } from './useTranslate.interface'

export const enMessages: Record<messageIds, string> = {
  'generic.inDevelopment': 'Under construction',
  'generic.submit': 'Submit',
  'generic.abort': 'Cancel',
  'navBar.expenses.label': 'My expenses',
  'navBar.earnings.label': 'My earnings',
  'navBar.admin.label': 'Administration',
  'navBar.logout.label': 'Logout',
  'navBar.logout.notify': 'You are now logged out',
  'navBar.theme.darkMode': 'Dark theme',
  'navBar.theme.lightMode': 'Light theme',
  'pages.home.lastMonth.expenseCategoryPie.title':
    'My expenses distribution during the last month',
  'pages.home.lastMonth.expenseTimeline.title':
    'My expenses evolution during the last month',
  'pages.home.lastYear.expenseAndEarning.title':
    'My expenses and earnings in the last year',
  'pages.expenses.label': 'My expenses',
  'pages.expenses.itemModal.new.title': 'New expense',
  'pages.expenses.table.label': 'List',
  'entities.expenses.fields.spentAt.label': 'Date',
  'entities.expenses.fields.expenseCategory.label': 'Category',
  'entities.expenses.fields.amount.label': 'Amount',
  'entities.expenses.fields.description.label': 'Description',
  'entities.expenses.fields.refund.label': 'Refund',
  'pages.expenses.graphs.label': 'Charts',
  'pages.expenses.graphs.refundDeduction.label': 'Subtract refunds',
  'pages.expenses.graphs.expenseCategoryPie.title': 'My expenses by category',
  'pages.expenses.graphs.expenseTimeline.title': 'My expenses through time',
  'pages.earnings.label': 'My earnings',
  'pages.earnings.itemModal.new.title': 'New earning',
  'pages.earnings.table.label': 'List',
  'entities.earnings.fields.earnedAt.label': 'Date',
  'entities.earnings.fields.earningCategory.label': 'Category',
  'entities.earnings.fields.amount.label': 'Amount',
  'entities.earnings.fields.description.label': 'Description',
  'pages.earnings.graphs.label': 'Charts',
  'pages.earnings.itemModal.onSuccess.notify': 'Earning saved',
  'pages.expenses.itemModal.onSuccess.notify': 'Expense saved',
  'pages.expenses.itemModal.hasRefund.label': 'Apply a refund',
  'entities.refunds.fields.earningCategory.label': 'Category',
  'entities.refunds.fields.amount.label': 'Amount',
  'entities.refunds.fields.description.label': 'Description',
  'pages.expenses.itemModal.edit.title': 'Edition of an expense',
  'pages.earnings.itemModal.edit.title': 'Edition of an earning',
}
