import { messageIds } from './useTranslate.interface'

export const enMessages: Record<messageIds, string> = {
  'generic.inDevelopment': 'Under construction',
  'generic.submit': 'Submit',
  'generic.abort': 'Cancel',
  'navBar.expenses.label': 'My expenses',
  'navBar.earnings.label': 'My earnings',
  'navBar.admin.label': 'Administration',
  'navBar.logout.label': 'Logout',
  'navBar.logout.notify': 'You are now logged out',
  'navBar.theme.darkMode': 'Dark theme',
  'navBar.theme.lightMode': 'Light theme',
  'pages.home.lastMonth.expenseCategoryPie.title':
    'My expenses distribution during the last month',
  'pages.home.lastMonth.expenseTimeline.title':
    'My expenses evolution during the last month',
  'pages.home.lastYear.expenseAndEarning.title':
    'My expenses and earnings in the last year',
  'pages.expenses.label': 'My expenses',
  'pages.expenses.itemModal.new.title': 'New expense',
  'pages.expenses.table.label': 'Expenses',
  'entities.expenses.fields.spentAt.label': 'Date',
  'entities.expenses.fields.expenseCategory.label': 'Category',
  'entities.expenses.fields.amount.label': 'Amount',
  'entities.expenses.fields.description.label': 'Description',
  'entities.expenses.fields.refund.label': 'Refund',
  'pages.expenses.graphs.label': 'Charts',
  'pages.expenses.graphs.refundDeduction.label': 'Subtract refunds',
  'pages.expenses.graphs.expenseCategoryPie.title': 'My expenses by category',
  'pages.expenses.graphs.expenseTimeline.title': 'My expenses through time',
  'pages.earnings.label': 'My earnings',
  'pages.earnings.itemModal.new.title': 'New earning',
  'pages.earnings.table.label': 'Earnings',
  'entities.earnings.fields.earnedAt.label': 'Date',
  'entities.earnings.fields.earningCategory.label': 'Category',
  'entities.earnings.fields.amount.label': 'Amount',
  'entities.earnings.fields.description.label': 'Description',
  'pages.earnings.graphs.label': 'Charts',
  'pages.earnings.itemModal.onSuccess.notify': 'Earning saved',
  'pages.expenses.itemModal.onSuccess.notify': 'Expense saved',
  'pages.expenses.itemModal.hasRefund.label': 'Apply a refund',
  'entities.refunds.fields.earningCategory.label': 'Category',
  'entities.refunds.fields.amount.label': 'Amount',
  'entities.refunds.fields.description.label': 'Description',
  'pages.expenses.itemModal.edit.title': 'Edition of an expense',
  'pages.earnings.itemModal.edit.title': 'Edition of an earning',
  'pages.expenses.categories.label': 'Sub-topic',
  'pages.expenses.categoryModal.new.title': 'New sub-topic',
  'pages.expenses.categoryModal.edit.title': 'Edition of a sub-topic',
  'entities.expenseCategories.fields.expenseCategoryGroup.label':
    'Expense topic',
  'entities.expenseCategories.fields.name.label': 'Name',
  'entities.expenseCategories.fields.description.label': 'Description',
  'pages.expenses.categoryModal.onSuccess.notify': 'Category saved',
  'pages.expenses.categoryGroups.label': 'Pôles de dépense',
  'pages.expenses.categoryGroupModal.new.title': 'New expense topic',
  'pages.expenses.categoryGroupModal.edit.title': 'Edition of an expense topic',
  'pages.expenses.categoryGroupModal.onSuccess.notify': 'Expense topic savec',
  'entities.expenseCategoryGroups.fields.name.label': 'Name',
  'entities.expenseCategoryGroups.fields.description.label': 'Description',
  'entities.earningCategories.fields.name.label': 'Name',
  'entities.earningCategories.fields.description.label': 'Description',
  'pages.earnings.categories.label': 'Earning sources',
  'pages.earnings.categoryModal.new.title': 'New earning source',
  'pages.earnings.categoryModal.edit.title': 'Edition of an earning source',
  'pages.earnings.categoryModal.onSuccess.notify': 'Earning source saved',
}
