import { messageIds } from './useTranslate.interface'

export const frMessages: Record<messageIds, string> = {
  'generic.inDevelopment': 'En cours de construction',
  'generic.submit': 'Valider',
  'generic.abort': 'Annuler',
  'navBar.expenses.label': 'Mes dépenses',
  'navBar.earnings.label': 'Mes recettes',
  'navBar.admin.label': 'Administration',
  'navBar.logout.label': 'Me déconnecter',
  'navBar.logout.notify': 'Vous êtes maintenant déconnecté',
  'navBar.theme.darkMode': 'Thème foncé',
  'navBar.theme.lightMode': 'Thème clair',
  'pages.home.lastMonth.expenseCategoryPie.title':
    'Répartition de mes dépenses depuis un mois',
  'pages.home.lastMonth.expenseTimeline.title':
    'Évolution de mes dépenses dépuis un mois',
  'pages.home.lastYear.expenseAndEarning.title':
    'Mes dépenses et recettes depuis un an',
  'pages.expenses.label': 'Mes dépenses',
  'pages.expenses.itemModal.new.title': 'Nouvelle dépense',
  'pages.expenses.table.label': 'Liste',
  'entities.expenses.fields.spentAt.label': 'Date',
  'entities.expenses.fields.expenseCategory.label': 'Catégorie',
  'entities.expenses.fields.amount.label': 'Montant',
  'entities.expenses.fields.description.label': 'Description',
  'entities.expenses.fields.refund.label': 'Remboursement',
  'pages.expenses.graphs.label': 'Graphiques',
  'pages.expenses.graphs.refundDeduction.label': 'Déduire les remboursements',
  'pages.expenses.graphs.expenseCategoryPie.title':
    'Mes dépenses par catégorie',
  'pages.expenses.graphs.expenseTimeline.title': 'Mes dépenses dans le temps',
  'pages.earnings.label': 'Mes recettes',
  'pages.earnings.itemModal.new.title': 'Nouvelle recette',
  'pages.earnings.table.label': 'Liste',
  'entities.earnings.fields.earnedAt.label': 'Date',
  'entities.earnings.fields.earningCategory.label': 'Catégorie',
  'entities.earnings.fields.amount.label': 'Montant',
  'entities.earnings.fields.description.label': 'Description',
  'pages.earnings.graphs.label': 'Graphiques',
  'pages.earnings.itemModal.onSuccess.notify': 'Recette enregistrée',
  'pages.expenses.itemModal.onSuccess.notify': 'Dépense enregistrée',
  'pages.expenses.itemModal.hasRefund.label': 'Appliquer a remboursement',
  'entities.refunds.fields.earningCategory.label': 'Catégorie',
  'entities.refunds.fields.amount.label': 'Montant',
  'entities.refunds.fields.description.label': 'Description',
  'pages.expenses.itemModal.edit.title': "Édition d'une dépense",
  'pages.earnings.itemModal.edit.title': "Édition d'une recette",
}
